version: '3'
services:
    database:
        image: mariadb
        networks:
            default:
            phpmyadmin:
                aliases:
                    - db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: hslcongestion
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks:
            - phpmyadmin
        ports:
            - 80
        depends_on:
            - database
    track_stop_times:
        image: node:10
        command: npm run track-stop-times
        working_dir: /usr/app
        volumes: &appvolumes
            - .:/usr/app
        networks:
            - default
        depends_on:
            - database
    api:
        image: node:10
        command: npm run api
        working_dir: /usr/app
        volumes: appvolumes
        networks:
            - default
        depends_on:
            - database
        environment:
            PORT: 80
        ports:
            - 80
networks:
    default:
    phpmyadmin:
